[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2024"
version = "0.1.0"

[profile.dev]
debug = 0
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = 0

[profile.dev.package.s3formats]
opt-level = 3

[profile.dev.package.s3pkg]
opt-level = 3

[profile.dev.package.s3bake]
opt-level = 3
