//! Which of the game's ~35,000 animation clips to bake: walks and idles, the start/loop/stop
//! clips of every supported object interaction, two-Sim social animations (both sides) and
//! their child equivalents. Clips are stored lz4-compressed in `clips.pack`, keyed by the
//! FNV-64 of the lowercased name, and decoded lazily by the game.

/// Clip-name prefixes to bake. Object and social clips must also end in `_x` / `_y` (the
/// Sim's side; other suffixes are the props').
pub const CLIP_PREFIXES: &[&str] = &[
    // Walks and idles.
    "a_female_walk",
    "a_male_walk",
    "a_male_jog",
    "a_female_walk_pregnant",
    // (The game's walk styles: fast walk, fast jog, run, fast run, on fire.)
    "a_male_fastjog",
    "a_male_run",
    "a_female_run",
    "c_run",
    "a_soc_callOver_x",
    "a2o_door_ringBell_x",
    "a2a_soc_Neutral_Greet_Friendly_Friendly",
    "a2a_soc_neutral_greet",
    "a_idle_neutral_",
    "a_idle_friendly_",
    "a_idle_wipeSweat",
    "a_idle_fanSelf",
    "a_dance_beg_",
    "a_dance_med_",
    "c_walk",
    "c_idle_neutral_",
    "c_idleBlend",
    // Kitchen.
    "a2o_fridge_openDoor",
    "a2o_fridge_closeDoor",
    "a2o_fridge_takeFoodOut_plateDinner",
    "a2o_fridge_takeFoodOut_foodTray_x",
    "a2o_fridge_takeFoodOut_foodTray_foodTray",
    "a2o_fridge_takeFoodOut_foodTray_fridge",
    "a2o_foodTray_carry",
    "a2o_carryObject_carry",
    "a2o_chairDining_getIn_x",
    "a2o_chairDining_getOut_x",
    "c2o_chairDining_getIn_x",
    "c2o_chairDining_getOut_x",
    "a2o_barstool_getIn_N_x",
    "a2o_barstool_getOut_N_x",
    "a2o_microwave_put",
    "a2o_microwave_get_",
    "a2o_microwave_check",
    "a2o_carryObject_putDown_counter",
    "a2o_fryingPan_carry",
    "a2o_cuttingBoard_start_fromCarry",
    "a2o_stove_fryingPan_start_fromCarry",
    "a2o_fridge_cookSomthing",
    "a2o_stove_fryingPan_start_fromNeutral",
    "a2o_stove_fryingPan_idle",
    "a2o_stove_fryingPan_spatula",
    "a2o_stove_fryingPan_pourPlate_x",
    "a2o_stove_clean",
    "a2o_eat_stand_fork",
    "a2o_eat_stand_hand",
    "a2o_eat_diningIn_fork",
    // Gardening.
    "a2o_gardening_",
    // Collecting and fishing.
    "a2o_collectionRock_analyze",
    "a2o_fishHereWith_cast_normal",
    "a2o_fishHereWith_idle",
    "a2o_catchFish_reelIn",
    "a2o_catchFish_react",
    // Homework at a table.
    "c2o_homework_table_",
    // Swimming, and the pool ladders.
    "a_swim_",
    "a_swim2stand",
    "a2o_ladder_climb",
    // Fireplaces.
    "a2o_fireplace_light_start",
    "a2o_fireplace_putOut",
    "a2o_fireplace_warmHands",
    // Fire pits, the urinal, the toy oven, the buffet, the picnic basket, the rubber duck.
    "a2o_firePit_light_start",
    "a2o_firePit_putOut",
    "a2o_firePit_warmHands",
    "a2o_firePit_roast_start",
    "a2o_firePit_roast_loop",
    "a2o_firePit_roast_stop",
    "a2o_firePit_roast_eat",
    "c2o_firePit_warmHands",
    "c2o_firePit_roast_start",
    "c2o_firePit_roast_loop",
    "c2o_firePit_roast_stop",
    "c2o_firePit_roast_eat",
    "a2o_urinal_useStanding",
    "a2o_urinal_flush_x",
    "c2o_easyBakeOven_prep_start_",
    "c2o_easyBakeOven_prep_loop",
    "c2o_easyBakeOven_prep_stopFinished",
    "a2o_buffetTable_serve",
    "c2o_buffetTable_serve",
    "a2o_picnicBasket_getPlate_part1",
    "a2o_picnicBasket_eat",
    "c2o_picnicBasket_getPlate_part1",
    "c2o_picnicBasket_eat",
    "a2o_bathtub_ducky",
    "c2o_bathtub_ducky",
    "a2a_soc_playCatch_throw",
    // Pets: cats, kittens, dogs, puppies, little dogs, horses and foals walking, trotting,
    // running, standing, sitting, lying about and asleep.
    "ac_walk_x",
    "ac_trot_x",
    "ac_run_x",
    "ac_idle_",
    "ac_sleep_loop",
    "cc_walk_x",
    "cc_trot_x",
    "cc_run_x",
    "cc_idle_",
    "cc_sleep_loop",
    "ad_walk_x",
    "ad_trot_x",
    "ad_run_x",
    "ad_idle_",
    "ad_sleep_loop",
    "cd_walk_x",
    "cd_trot_x",
    "cd_run_x",
    "cd_idle_",
    "cd_sleep_loop",
    "al_walk_x",
    "al_trot_x",
    "al_run_x",
    "al_idle_",
    "al_sleep_loop",
    "ah_walk_x",
    "ah_trot_x",
    "ah_run_x",
    "ah_idle_",
    "ah_sleep_loop",
    "ch_walk_x",
    "ch_trot_x",
    "ch_run_x",
    "ch_idle_",
    "ch_sleep_loop",
    // Sims with pets: petting, letting them sniff a hand, praise, hugs, treats, rubbing a
    // horse's neck, scolding (both sides).
    "a2ac_soc_neutral_",
    "a2cc_soc_neutral_",
    "a2ad_soc_neutral_",
    "a2cd_soc_neutral_",
    "a2al_soc_neutral_",
    "a2ah_soc_neutral_",
    "a2ch_soc_neutral_",
    "c2ac_soc_neutral_",
    "c2ad_soc_neutral_",
    "c2al_soc_neutral_",
    "c2ah_soc_neutral_",
    // The packs' games and instruments: pool, darts, bowling, karaoke, the arcade machines,
    // skee-ball, horseshoes, shuffleboard, the mechanical bull, trampolines, sandboxes, the
    // piano and keyboard, drums and the laser harp.
    "a2o_poolTable_play8_p1_",
    "a2o_poolTable_play8_idle_",
    "a2o_poolTable_play8_transOutIdle",
    "a2o_dartboard_throw_",
    "a2o_bowlingLane_getBall",
    "a2o_bowlingLane_lowSkillThrow_throw",
    "a2o_bowlingLane_throw_slow",
    "a2o_bowlingLane_end",
    "a2o_karaoke_singSolo",
    "c2o_karaoke_singSolo",
    "a2o_arcadeMachine_",
    "c2o_arcadeMachine_",
    "a2o_arcadeClawMachine_",
    "c2o_arcadeClawMachine_",
    "a2o_arcadeWhackAGnome_",
    "c2o_arcadeWhackAGnome_",
    "a2o_skeeBall_",
    "c2o_skeeBall_",
    "a2o_horseshoeCourt_",
    "a2o_shuffleboard_shoot",
    "a2o_mechanicalBull_ride_",
    "a2o_mechanicalBull_dismount_success",
    "a2o_trampoline_",
    "c2o_trampoline_",
    "a2o_piano_play_",
    "c2o_piano_play_",
    "a2o_keyboard_play_",
    "c2o_keyboard_play_",
    "a2o_drum_play_",
    "c2o_drum_play_",
    "a2o_laserHarp_",
    "c2o_laserHarp_",
    "a2o_sandbox_play_",
    "c2o_sandbox_play_",
    // Supernaturals: werewolves' and zombies' walks and idles, werewolves turning and howling,
    // vampires' runs and the sun, plasma, and their socials and spells.
    "a_werewolf_walk",
    "a_werewolf_run",
    "a_werewolf_idle",
    "a_werewolf_trans2",
    "a_werewolf_howlAtMoon",
    "a_zombie_walk",
    "a_zombie_idle",
    "a_zombie_graaains",
    "a_vampires_run",
    "a_vampires_tooMuchSun",
    "a_vampires_idle",
    "a2o_vampires_drinkPotion",
    "a2a_soc_vampire_hypnoticGaze_success",
    "a2a_soc_vampire_talkAboutJoyOfPlasma_accept",
    "a2a_soc_fairy_frolic",
    "a2a_fairy_playTrick_hotHead",
    "a2a_soc_fairy_bragAboutWings_accept",
    "a2a_soc_fairy_talkAboutFlightExperience_accept",
    "a2a_soc_werewolf_practiceFighting_accept",
    "a2a_soc_werewolf_rubBelly",
    "a2a_magicWand_castSpell_lowSkill_start",
    "a2a_magicWand_castSpell_lowSkill_loop",
    "a2a_magicWand_castSpell_lowSkill_success",
    // Seasons: snowmen, snow angels, catching snowflakes and raindrops, leaf piles.
    "a2o_snowman_build",
    "c2o_snowman_build",
    "a2o_snowman_destroy",
    "c2o_snowman_destroy",
    "a2o_snowAngel_make",
    "c2o_snowAngel_make",
    "a2o_snowAngel_destroy",
    "c2o_snowAngel_destroy",
    "a_idle_catchSnow",
    "c_idle_catchSnow",
    "a_idle_catchRain",
    "c_idle_catchRain",
    "a2o_leafPile_playIn",
    "c2o_leafPile_playIn",
    "a2o_leafPile_jumpCannonBall",
    "c2o_leafPile_jumpCannonBall",
    "a2o_leafPile_rake",
    "c2o_leafPile_rake",
    // Catching butterflies and beetles.
    "a2o_butterfly_catch",
    "a2o_beetle_catch",
    "c2o_butterfly_catch",
    "c2o_beetle_catch",
    // Fire.
    "a_fire_panic",
    "a_fire_onFire",
    "a_fireFighter_extinguishFire_floor1",
    // Ghosts, and the frights they give.
    "a_ghost_float",
    "a_ghost_scare",
    "a_react_startled",
    // Burglars and the police.
    "a2o_burglar_steal",
    "a2o_burglar_sneak",
    "a2a_burglar_cuff",
    // Repairs.
    "a2o_toilet_unclog",
    "a2o_shower_repairShower",
    "a2o_bathtub_repair",
    "a2o_sink_repair",
    "a2o_tv_repair",
    "a2o_computer_repair",
    "a2o_stereo_repair",
    "a2o_dishwasher_repair_loopTinker",
    // Phone calls on the cell phone: taking it out, chatting, putting it away.
    "a2o_phone_makeCall_cellPhone",
    "a2o_phone_chat_",
    "a2o_phone_hangUp_cellPhone",
    // The mailbox and the paper.
    "a2o_mailbox_getMail",
    "a2o_mailbox_putFlagUp",
    // Need failures: an accident, collapsing from exhaustion, sleeping on the floor.
    "a_motFail_",
    "c_motFail_",
    "a_sleeponFloor_",
    "c_sleeponFloor_",
    "t_sleeponFloor_",
    "a2o_newspaper_read",
    // The Grim Reaper and dying of old age.
    "a_death_appear",
    // Blowing out a birthday cake's candles, and cheering them on.
    "a2o_birthdayCake_blowOut",
    "c2o_birthdayCake_blowOut",
    "a2o_birthdayCake_cheer",
    // Dying of hunger or electrocution, and the shock from a botched repair.
    "a_die_starvation",
    "a_die_electrocution",
    "a_die_drowning",
    "c_die_drowning",
    "a2o_handiness_fail_electrocution",
    "a_death_float",
    "a_death_create",
    "e_die_oldAge",
    "a2o_eat_barStoolIn_fork",
    // Bathroom.
    "a2o_toilet_useStanding",
    "a2o_toilet_flush_x",
    "a2o_shower_takeShower_getIn",
    "a2o_shower_takeShower_loop",
    "a2o_shower_takeShower_getOut",
    "a2o_bathtub_relax",
    "a2o_sink_washhands",
    "a2o_sink_brushTeeth",
    // Beds and seating.
    "a2o_bed_getIn_made",
    "a2o_bed_getout",
    "a2o_bed_nap",
    "a2o_bed_sleep",
    "a2o_bed_trans_relax2sleep",
    "a2o_bed_relax_loop",
    "a2o_bed_relax_getin",
    "a2o_chairLiving_sit_breathe",
    "a2o_chairLiving_sit_crossedLeg_front",
    "a2o_sitTemplate_sit_loopBreathe",
    "a2o_sofa_",
    // Electronics, hobbies, skills.
    "a2o_tv_watch_",
    "a2o_computer_game_loop",
    "a2o_computer_chess_type_loop",
    "a2o_book_readBook_standing",
    "a2o_book_readBook_sitting",
    "c2o_book_readBook_sitting",
    "c2o_book_readBook_standing",
    "a2o_book_carry_x",
    "a2o_book_carry_book",
    "c2o_book_carry_x",
    "c2o_book_carry_book",
    "a2o_bookshelf_getBook_Carry",
    "a2o_newspaper_pickUp_floor",
    "a2o_newspaper_carry_x",
    "a2o_newspaper_carry_newspaper",
    "c2o_bookshelf_getBook_Carry",
    "a2o_mirror_full_checkSelfOut",
    "a2o_painting_start",
    "a2o_painting_loopMed",
    "a2o_painting_loopLarge",
    "a2o_painting_consider",
    "a2o_painting_stop",
    "a2o_holographicEasel_loopMed",
    "a2o_guitar_play_",
    "a2o_treadmill_jog",
    "a2o_chessTable_loop",
    "a2o_chessTable_move",
    "a2o_phone_call_loopBreathe",
    "a2o_phone_chat_talk",
    // Socials (both sides).
    "a2a_soc_Neutral_Gossip_Friendly_Neutral",
    "a2a_soc_Neutral_RambleAimlessly_talk",
    "a2a_soc_neutral_tellJoke_accept",
    "a2a_soc_neutral_tellJoke_reject",
    "a2a_soc_Neutral_Compliment_Friendly",
    "a2a_soc_Neutral_Compliment_Amorous",
    "a2a_soc_friendly_hug_accept",
    "a2a_soc_Neutral_FriendlyHug_Friendly_Neutral",
    "a2a_soc_neutral_highFive_friendly_neutral",
    "a2a_soc_neutral_probe_tickle",
    "a2a_soc_Neutral_Flirt_Neutral_Neutral",
    "a2a_soc_Neutral_Flirt_Amorous_Amorous",
    "a2a_soc_Amorous_HoldHands_Affectionate_Amorous",
    "a2a_soc_Amorous_ShyKiss_Amorous_Amorous",
    "a2a_soc_amorous_kissMakeOut_accept",
    "a2a_soc_amorous_kissRomantic_romantic_amorous",
    "a2a_soc_Amorous_ProposeMarriage_Amorous_Amorous",
    "a2a_soc_Amorous_ProposeWedding_Accept",
    "a2a_soc_Amorous_Wedding_Amorous_Amorous",
    "a2a_soc_Bad_Mock_Insulting_Bad",
    "a2a_soc_Bad_Accuse_Insulting_Bad",
    "a2a_soc_Bad_Slap_Steamed_Bad",
    "a2a_soc_Neutral_BreakUp_Neutral_Neutral",
    "a2a_soc_Neutral_TellFunnyStory_Funny_Friendly",
    "a2a_soc_Neutral_TellDramaticStory_Impressive_Neutral",
    "a2a_soc_Neutral_BoastAbout_Impressive_Friendly",
    "a2a_soc_Neutral_GoofAround_Funny_Neutral",
    "a2a_soc_Neutral_MakeSillyFace_Funny_Neutral",
    "a2a_soc_Neutral_CryOnShoulder_Friendly_Neutral",
    "a2a_soc_Neutral_CheerUp_Friendly_Neutral",
    "a2a_soc_Neutral_Apologize_Awkward_Neutral",
    "a2a_soc_Bad_Fight_",
    "a2a_soc_bad_YellAt_Steamed_Bad",
    "a2a_soc_bad_irritate_insulting_bad",
    "a2a_soc_Bad_DeclareNemesis_Steamed_Bad",
    "a2a_soc_Amorous_Embrace_Amorous_Amorous",
    "a2a_soc_Amorous_GazeIntoEyes_Amorous_Amorous",
    "a2a_soc_Amorous_Massage_Amorous_",
    "a2a_soc_Amorous_LeapIntoArms_Amorous_Amorous",
    "a2a_soc_amorous_dipKiss_amorous_amorous",
    "a2a_bed_cuddle_woohoo",
    "a2a_danceClub_dance_medSkill_loop1",
    // Children.
    "c2o_bed_getIn_made",
    "c2o_bed_getout",
    "c2o_bed_nap",
    "c2o_bed_sleep",
    "c2o_toilet",
    "c2o_shower_takeShower",
    "c2o_fridge_openDoor",
    "c2o_tv_watch_",
    "c2o_computer_game_loop",
    // Toddlers.
    "p_walk",
    "p_crawl",
    "a2p_teachToWalk_",
    "a2p_teachToTalk_",
    "p_idle_neutral_loop",
    "p_idle_friendly_loop",
    "p_idle_breathe_x",
    "p_crawl_x",
    "p2o_crib_",
    "p2o_toyXylophone_play_",
    "p2o_toyPegBox_play_",
    "p2o_toybox_playIn_",
    "p2o_highChair_",
    // Babies.
    "b_idle_breathe",
    "b_sleep_beingHeld_y",
    "b_motDistress_cry_carry",
    "b2o_crib_",
    // Grown-ups looking after them.
    "a2b_crib_putIn",
    // More things to do at home.
    "a2o_dresser_use_",
    "c2o_dresser_use_",
    "a2o_telescope_",
    "a2o_swingset_",
    "c2o_swingset_",
    "a2o_hotTub_",
    "c2o_dollhouse_play_",
    "c2o_JungleGym",
    "a2o_foosballTable_play",
    "a2o_videoGame_sitFloor_",
    "c2o_videoGame_sitFloor_",
    "a2o_Vrgoggles_",
    "a2o_stuffedAnimal_play_loop",
    "c2o_stuffedAnimal_play_loop",
    "p2o_stuffedAnimal_play_loop",
    "c2o_stuffedAnimal_play_start_normal",
    "p2o_stuffedAnimal_play_start_normal",
    "a2o_sprinklerGarden_playWith_",
    "c2o_sprinklerGarden_playWith_",
    "a2o_divingBoard_",
    "c2o_divingBoard_",
    "a2o_bar_makeDrink_",
    "a2o_lifetimeReward_foodReplicator",
    "a2o_bodySculptor_",
    "c2o_bodySculptor_",
    "a2o_hotBeverageMachine_fill",
    "a2o_bbq_grill_",
    "a2o_cuttingBoard_chop_",
    "a2o_homework_table_",
    "c2o_homework_table_",
    "a2o_trashCan_empty",
    "c2o_trashCan_empty",
    "a2o_hotBeverageMachine_drink_loop",
    "a2o_dishwasher_use",
    "a2o_object_genericSwipe",
    "a2o_trashPile_carry",
    "a2o_trashPile_drop_outdoors_x",
    "a2o_trashPile_drop_outdoors_trashbag",
    "a2o_dishwasher_repair_start_kneel",
    "a2o_dishwasher_repair_loopInspect",
    "a2o_sink_dishes_scrub",
    "a2o_trashCompactor_takeOut",
    "c2o_trashCompactor_takeOut",
    "a2o_plateDinner_pickUp_table",
    "a2o_plateDinner_carry",
    "a2b_crib_pullOut",
    "a2b_babyBottle_feed",
    "a2b_changeDiaper",
    "a2b_carryPose",
    "a2b_idle_carry_",
    "a2b_pickUp",
    "a2p_idle_carry_",
    "a2p_carryPose",
    "a2p_crib_putIn",
    "a2p_crib_pullOut",
    "a2p_carry_chat_",
    "a2p_pickUp",
    "a2p_changeDiaper",
    "a2p_highChair_",
    "a2p_book_readWith_",
    "a2p_babyBottle_giveTake",
];

/// Clip actors that are props held by the Sim (baked with the Sim's clips).
pub const PROP_ACTORS: &[&str] = &[
    "fork",
    "plateDinner",
    "book",
    "toothbrush",
    "guitar",
    "spatula",
    "scythe",
    "newspaperReading",
    "bills",
    "wateringCan",
    "fishingPole",
    "fishingRod",
    "fireExtinguisher",
    "bag",
    "phone",
    "phone1",
    "VGcontroller",
    "VGcontroller2",
    "vrGoggles",
    "stuffedAnimal",
    "coffeeCup",
    "blender",
    "glassBar01",
    "glassBar",
    "plate",
    "carryObject",
    "foodTray",
    "fryingPan",
    "cuttingBoard",
    "knife",
    "cookingKnife",
    "newspaper",
    "newspaperRolled",
    "trashbag",
    "wrench",
    "firePitSkewer",
    "fireplaceLighter",
    "poker",
    "mixingBowl",
    "spoon",
    "platePaper",
    "hamburger",
    "ducky",
    "baseball",
    "rake",
    "snowBallAccessory",
    "treat",
    "wand",
    "cue",
    "mic",
    "dartInHand",
    "bowlingBall",
    "drumStick",
    "drumStick1",
    "horseShoe",
    "puckInHand",
    "arcadeWhackAGnomeMallet",
];

/// Objects' own halves of clips whose actor isn't named for the object (the pool table's
/// `_pool`, the drum kit's `_drumKit`).
pub const OBJECT_ACTORS: &[&str] = &["pool", "arcadeClaw", "bull", "drumKit"];

/// Whether a clip should be baked.
pub fn wanted(name: &str) -> bool {
    // (The Sim's side, a prop's, or the object's own: `a2o_fridge_openDoor_fridge` swings its
    // door as the Sim opens it.)
    let actor_side = |n: &str| {
        n.ends_with("_x")
            || n.ends_with("_y")
            || n.rsplit_once('_').is_some_and(|(_, a)| {
                PROP_ACTORS.iter().chain(OBJECT_ACTORS).any(|p| p.eq_ignore_ascii_case(a)) || n.split('_').nth(1).is_some_and(|o| o.eq_ignore_ascii_case(a))
            })
    };
    CLIP_PREFIXES.iter().any(|p| {
        if !name.starts_with(p) {
            return false;
        }
        let object_or_social = ["a2o_", "a2a_", "c2o_", "p2o_", "b2o_", "a2b_", "a2p_"].iter().any(|p| name.starts_with(p));
        !object_or_social || actor_side(name)
    })
}

/// Pack key of a clip by name.
pub fn clip_key(name: &str) -> crate::types::Key {
    (s3pkg::types::CLIP, 0, s3pkg::fnv64(&name.to_ascii_lowercase()))
}
