//! Which of the game's ~35,000 animation clips to bake: walks and idles, the start/loop/stop
//! clips of every supported object interaction, two-Sim social animations (both sides) and
//! their child equivalents. Clips are stored lz4-compressed in `clips.pack`, keyed by the
//! FNV-64 of the lowercased name, and decoded lazily by the game.

/// Clip-name prefixes to bake. Object and social clips must also end in `_x` / `_y` (the
/// Sim's side; other suffixes are the props').
pub const CLIP_PREFIXES: &[&str] = &[
    // Walks and idles.
    "a_female_walk",
    "a_male_walk",
    "a_idle_neutral_",
    "a_idle_friendly_",
    "a_idle_wipeSweat",
    "a_idle_fanSelf",
    "a_dance_beg_",
    "a_dance_med_",
    "c_walk",
    "c_idle_neutral_",
    "c_idleBlend",
    // Kitchen.
    "a2o_fridge_openDoor",
    "a2o_fridge_closeDoor",
    "a2o_fridge_cookSomthing",
    "a2o_stove_fryingPan_start_fromNeutral",
    "a2o_stove_fryingPan_idle",
    "a2o_stove_fryingPan_spatula",
    "a2o_stove_fryingPan_pourPlate_x",
    "a2o_stove_clean",
    "a2o_eat_stand_fork",
    "a2o_eat_stand_hand",
    "a2o_eat_diningIn_fork",
    // Gardening.
    "a2o_gardening_",
    // Collecting and fishing.
    "a2o_collectionRock_analyze",
    "a2o_fishHereWith_cast_normal",
    "a2o_fishHereWith_idle",
    "a2o_catchFish_reelIn",
    "a2o_catchFish_react",
    // Homework at a table.
    "c2o_homework_table_",
    // Swimming, and the pool ladders.
    "a_swim_",
    "a_swim2stand",
    "a2o_ladder_climb",
    // Fireplaces.
    "a2o_fireplace_light_start",
    "a2o_fireplace_putOut",
    "a2o_fireplace_warmHands",
    // Catching butterflies and beetles.
    "a2o_butterfly_catch",
    "a2o_beetle_catch",
    "c2o_butterfly_catch",
    "c2o_beetle_catch",
    // Fire.
    "a_fire_panic",
    "a_fire_onFire",
    "a_fireFighter_extinguishFire_floor1",
    // Ghosts, and the frights they give.
    "a_ghost_float",
    "a_ghost_scare",
    "a_react_startled",
    // Burglars and the police.
    "a2o_burglar_steal",
    "a2o_burglar_sneak",
    "a2a_burglar_cuff",
    // Repairs.
    "a2o_toilet_unclog",
    "a2o_shower_repairShower",
    "a2o_bathtub_repair",
    "a2o_sink_repair",
    "a2o_tv_repair",
    "a2o_computer_repair",
    "a2o_stereo_repair",
    "a2o_dishwasher_repair_loopTinker",
    // Phone calls on the cell phone: taking it out, chatting, putting it away.
    "a2o_phone_makeCall_cellPhone",
    "a2o_phone_chat_",
    "a2o_phone_hangUp_cellPhone",
    // The mailbox and the paper.
    "a2o_mailbox_getMail",
    "a2o_mailbox_putFlagUp",
    // Need failures: an accident, collapsing from exhaustion, sleeping on the floor.
    "a_motFail_",
    "c_motFail_",
    "a_sleeponFloor_",
    "c_sleeponFloor_",
    "t_sleeponFloor_",
    "a2o_newspaper_read",
    // The Grim Reaper and dying of old age.
    "a_death_appear",
    // Blowing out a birthday cake's candles, and cheering them on.
    "a2o_birthdayCake_blowOut",
    "c2o_birthdayCake_blowOut",
    "a2o_birthdayCake_cheer",
    // Dying of hunger or electrocution, and the shock from a botched repair.
    "a_die_starvation",
    "a_die_electrocution",
    "a2o_handiness_fail_electrocution",
    "a_death_float",
    "a_death_create",
    "e_die_oldAge",
    "a2o_eat_barStoolIn_fork",
    // Bathroom.
    "a2o_toilet_useStanding",
    "a2o_toilet_flush_x",
    "a2o_shower_takeShower_getIn",
    "a2o_shower_takeShower_loop",
    "a2o_shower_takeShower_getOut",
    "a2o_bathtub_relax",
    "a2o_sink_washhands",
    "a2o_sink_brushTeeth",
    // Beds and seating.
    "a2o_bed_getIn_made",
    "a2o_bed_getout",
    "a2o_bed_nap",
    "a2o_bed_sleep",
    "a2o_bed_trans_relax2sleep",
    "a2o_bed_relax_loop",
    "a2o_bed_relax_getin",
    "a2o_chairLiving_sit_breathe",
    "a2o_chairLiving_sit_crossedLeg_front",
    "a2o_sitTemplate_sit_loopBreathe",
    "a2o_sofa_",
    // Electronics, hobbies, skills.
    "a2o_tv_watch_",
    "a2o_computer_game_loop",
    "a2o_computer_chess_type_loop",
    "a2o_book_readBook_standing",
    "a2o_mirror_full_checkSelfOut",
    "a2o_painting_start",
    "a2o_painting_loopMed",
    "a2o_painting_loopLarge",
    "a2o_painting_consider",
    "a2o_painting_stop",
    "a2o_holographicEasel_loopMed",
    "a2o_guitar_play_",
    "a2o_treadmill_jog",
    "a2o_chessTable_loop",
    "a2o_chessTable_move",
    "a2o_phone_call_loopBreathe",
    "a2o_phone_chat_talk",
    // Socials (both sides).
    "a2a_soc_Neutral_Gossip_Friendly_Neutral",
    "a2a_soc_Neutral_RambleAimlessly_talk",
    "a2a_soc_neutral_tellJoke_accept",
    "a2a_soc_neutral_tellJoke_reject",
    "a2a_soc_Neutral_Compliment_Friendly",
    "a2a_soc_Neutral_Compliment_Amorous",
    "a2a_soc_friendly_hug_accept",
    "a2a_soc_Neutral_FriendlyHug_Friendly_Neutral",
    "a2a_soc_neutral_highFive_friendly_neutral",
    "a2a_soc_neutral_probe_tickle",
    "a2a_soc_Neutral_Flirt_Neutral_Neutral",
    "a2a_soc_Neutral_Flirt_Amorous_Amorous",
    "a2a_soc_Amorous_HoldHands_Affectionate_Amorous",
    "a2a_soc_Amorous_ShyKiss_Amorous_Amorous",
    "a2a_soc_amorous_kissMakeOut_accept",
    "a2a_soc_amorous_kissRomantic_romantic_amorous",
    "a2a_soc_Amorous_ProposeMarriage_Amorous_Amorous",
    "a2a_soc_Amorous_ProposeWedding_Accept",
    "a2a_soc_Amorous_Wedding_Amorous_Amorous",
    "a2a_soc_Bad_Mock_Insulting_Bad",
    "a2a_soc_Bad_Accuse_Insulting_Bad",
    "a2a_soc_Bad_Slap_Steamed_Bad",
    "a2a_soc_Neutral_BreakUp_Neutral_Neutral",
    "a2a_soc_Neutral_TellFunnyStory_Funny_Friendly",
    "a2a_soc_Neutral_TellDramaticStory_Impressive_Neutral",
    "a2a_soc_Neutral_BoastAbout_Impressive_Friendly",
    "a2a_soc_Neutral_GoofAround_Funny_Neutral",
    "a2a_soc_Neutral_MakeSillyFace_Funny_Neutral",
    "a2a_soc_Neutral_CryOnShoulder_Friendly_Neutral",
    "a2a_soc_Neutral_CheerUp_Friendly_Neutral",
    "a2a_soc_Neutral_Apologize_Awkward_Neutral",
    "a2a_soc_Bad_Fight_",
    "a2a_soc_bad_YellAt_Steamed_Bad",
    "a2a_soc_bad_irritate_insulting_bad",
    "a2a_soc_Bad_DeclareNemesis_Steamed_Bad",
    "a2a_soc_Amorous_Embrace_Amorous_Amorous",
    "a2a_soc_Amorous_GazeIntoEyes_Amorous_Amorous",
    "a2a_soc_Amorous_Massage_Amorous_",
    "a2a_soc_Amorous_LeapIntoArms_Amorous_Amorous",
    "a2a_soc_amorous_dipKiss_amorous_amorous",
    "a2a_bed_cuddle_woohoo",
    "a2a_danceClub_dance_medSkill_loop1",
    // Children.
    "c2o_bed_getIn_made",
    "c2o_bed_getout",
    "c2o_bed_nap",
    "c2o_bed_sleep",
    "c2o_toilet",
    "c2o_shower_takeShower",
    "c2o_fridge_openDoor",
    "c2o_tv_watch_",
    "c2o_computer_game_loop",
    // Toddlers.
    "p_walk",
    "p_crawl",
    "a2p_teachToWalk_",
    "a2p_teachToTalk_",
    "p_idle_neutral_loop",
    "p_idle_friendly_loop",
    "p_idle_breathe_x",
    "p_crawl_x",
    "p2o_crib_",
    "p2o_toyXylophone_play_",
    "p2o_toyPegBox_play_",
    "p2o_toybox_playIn_",
    "p2o_highChair_",
    // Babies.
    "b_idle_breathe",
    "b_sleep_beingHeld_y",
    "b_motDistress_cry_carry",
    "b2o_crib_",
    // Grown-ups looking after them.
    "a2b_crib_putIn",
    // More things to do at home.
    "a2o_dresser_use_",
    "c2o_dresser_use_",
    "a2o_telescope_",
    "a2o_swingset_",
    "c2o_swingset_",
    "a2o_hotTub_",
    "c2o_dollhouse_play_",
    "c2o_JungleGym",
    "a2o_foosballTable_play",
    "a2o_videoGame_sitFloor_",
    "c2o_videoGame_sitFloor_",
    "a2o_Vrgoggles_",
    "a2o_stuffedAnimal_play_loop",
    "c2o_stuffedAnimal_play_loop",
    "p2o_stuffedAnimal_play_loop",
    "c2o_stuffedAnimal_play_start_normal",
    "p2o_stuffedAnimal_play_start_normal",
    "a2o_sprinklerGarden_playWith_",
    "c2o_sprinklerGarden_playWith_",
    "a2o_divingBoard_",
    "c2o_divingBoard_",
    "a2o_bar_makeDrink_",
    "a2o_hotBeverageMachine_fill",
    "a2o_bbq_grill_",
    "a2o_cuttingBoard_chop_",
    "a2o_homework_table_",
    "c2o_homework_table_",
    "a2o_trashCan_empty",
    "c2o_trashCan_empty",
    "a2o_hotBeverageMachine_drink_loop",
    "a2b_crib_pullOut",
    "a2b_babyBottle_feed",
    "a2b_changeDiaper",
    "a2b_carryPose",
    "a2b_idle_carry_",
    "a2b_pickUp",
    "a2p_idle_carry_",
    "a2p_carryPose",
    "a2p_crib_putIn",
    "a2p_crib_pullOut",
    "a2p_carry_chat_",
    "a2p_pickUp",
    "a2p_changeDiaper",
    "a2p_highChair_",
    "a2p_book_readWith_",
    "a2p_babyBottle_giveTake",
];

/// Clip actors that are props held by the Sim (baked with the Sim's clips).
pub const PROP_ACTORS: &[&str] = &[
    "fork",
    "plateDinner",
    "book",
    "toothbrush",
    "guitar",
    "spatula",
    "scythe",
    "newspaperReading",
    "bills",
    "wateringCan",
    "fishingPole",
    "fishingRod",
    "fireExtinguisher",
    "bag",
    "phone",
    "phone1",
    "VGcontroller",
    "VGcontroller2",
    "vrGoggles",
    "stuffedAnimal",
    "coffeeCup",
    "blender",
    "glassBar01",
    "glassBar",
];

/// Whether a clip should be baked.
pub fn wanted(name: &str) -> bool {
    let actor_side = |n: &str| {
        n.ends_with("_x") || n.ends_with("_y") || n.rsplit_once('_').is_some_and(|(_, a)| PROP_ACTORS.iter().any(|p| p.eq_ignore_ascii_case(a)))
    };
    CLIP_PREFIXES.iter().any(|p| {
        if !name.starts_with(p) {
            return false;
        }
        let object_or_social = ["a2o_", "a2a_", "c2o_", "p2o_", "b2o_", "a2b_", "a2p_"].iter().any(|p| name.starts_with(p));
        !object_or_social || actor_side(name)
    })
}

/// Pack key of a clip by name.
pub fn clip_key(name: &str) -> crate::types::Key {
    (s3pkg::types::CLIP, 0, s3pkg::fnv64(&name.to_ascii_lowercase()))
}
